### PR TITLE
Hello microverse

### PR DESCRIPTION
**Pull request by cynthiainga**
**In this project 1:**

- set up linters
- added an Html and CSS files
- added a test.md file and added it to .gitignore
- added the template README md file

### CODE REVIEW

**Comment by cynthiainga** [comment]
When I changed the name of my branch, the first branch was closed, and another branch is created automatically.
But the first requests to change are in the pull request close.

**Review by Whoistolu — CHANGES_REQUESTED** [review]
Hi @cynthiainga,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [ ] Kindly make sure that your README.md file is descriptive. It should have your project details e.g your GitHub handle, LinkedIn handle, Twitter handle, the project title, project description, the project screenshot, the frameworks involved. What you currently have is just an empty template.

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._

**Comment by cynthiainga** [comment]
Now my README.md file is descriptive.

**Review by Meltrust — APPROVED** [review]
Hi @cynthiainga, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
